language: go
go:
  - '1.13.7'
go_import_path: github.com/cisco-sso/kdk
services:
  - docker
before_install:
  - make checks
script:
  - make bin-build docker-build
deploy:
  - on:
      tags: true
    provider: script
    script:
      - make docker-push bin-push
    skip_cleanup: true
