language: go
go:
- 1.13.7
go_import_path: github.com/cisco-sso/kdk
services:
- docker
before_install:
- "echo 'Removing travis-ci configuration of docker repository mirror'"
- sudo cat /etc/docker/daemon.json
- "echo '{\"mtu\": 1460}' | sudo tee /etc/docker/daemon.json"
- sudo systemctl restart docker
- sudo cat /etc/docker/daemon.json
- make checks
script:
- make bin-build docker-build
deploy:
- true:
    tags: true
  provider: script
  script:
  - make docker-push bin-push
  skip_cleanup: true
dist: focal
