[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/codeskyblue/go-sh"
  version = "0.2.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
